unbind C-b
set -g prefix C-f
bind -r C-f send-prefix

setw -g aggressive-resize on
set -sg escape-time 0
set -g mode-keys vi
set -g status-keys vi
set -g mouse on
set -g base-index 1
set -g renumber-windows on
set -g history-limit 10000
set -g default-terminal "rxvt-unicode-256color"

set -g status-bg 0
set -g status-fg 6
set -g status-left-length 30
set -g status-right " #(date '+%a %b %d, %Y  %I:%M %p') "

bind r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded"

bind -t vi-copy v begin-selection
bind -t vi-copy y copy-pipe "xclip -i -selection clipboard"
bind p run "xclip -o -selection clipboard | tmux load-buffer - ; tmux paste-buffer"

# Smart pane switching with awareness of vim splits
# See: https://github.com/christoomey/vim-tmux-navigator
is_vim='echo "#{pane_current_command}" | grep -iqE "(^|\/)g?(view|n?vim?x?)(diff)?$"'
bind -n C-h if-shell "$is_vim" "send-keys C-h" "select-pane -L"
bind -n C-j if-shell "$is_vim" "send-keys C-j" "select-pane -D"
bind -n C-k if-shell "$is_vim" "send-keys C-k" "select-pane -U"
bind -n C-l if-shell "$is_vim" "send-keys C-l" "select-pane -R"
bind -n C-\ if-shell "$is_vim" "send-keys C-\\" "select-pane -l"

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind -r { swap-window -t -1
bind -r } swap-window -t +1

bind -r < swap-pane -U
bind -r > swap-pane -D

bind Enter new-window
bind c split-window -h
bind C split-window -v

bind x kill-pane
bind X kill-session
